"""changge

Revision ID: 0893a714a376
Revises: 296c80a9d6e8
Create Date: 2021-06-14 01:21:16.185099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0893a714a376'
down_revision = '296c80a9d6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin_power', 'admin_power', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'admin_role_power', 'admin_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'admin_role_power', 'admin_power', ['power_id'], ['id'])
    op.create_foreign_key(None, 'admin_user_role', 'admin_role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'admin_user_role', 'admin_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_user_role', type_='foreignkey')
    op.drop_constraint(None, 'admin_user_role', type_='foreignkey')
    op.drop_constraint(None, 'admin_role_power', type_='foreignkey')
    op.drop_constraint(None, 'admin_role_power', type_='foreignkey')
    op.drop_constraint(None, 'admin_power', type_='foreignkey')
    # ### end Alembic commands ###
