"""empty message

Revision ID: 58fc2c4c30a5
Revises: 715a8ecc5856
Create Date: 2021-03-19 21:31:06.761526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fc2c4c30a5'
down_revision = '715a8ecc5856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role', sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role', 'enable')
    # ### end Alembic commands ###
