"""empty message

Revision ID: 816f66c2def4
Revises: ce8825111f8f
Create Date: 2021-03-14 22:57:37.092157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816f66c2def4'
down_revision = 'ce8825111f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_admin_log', sa.Column('success', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_admin_log', 'success')
    # ### end Alembic commands ###
