"""empty message

Revision ID: 83be574320e4
Revises: b5f015728218
Create Date: 2021-02-20 00:11:09.465217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83be574320e4'
down_revision = 'b5f015728218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'ext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('ext', mysql.CHAR(collation='utf8mb4_bin', length=10), nullable=False))
    # ### end Alembic commands ###
