"""empty message

Revision ID: 8b664608a7c7
Revises: ec21e19825ff
Create Date: 2021-06-01 14:37:20.327189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b664608a7c7'
down_revision = 'ec21e19825ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_dept',
    sa.Column('id', sa.Integer(), nullable=False, comment='部门ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级编号'),
    sa.Column('dept_name', sa.String(length=50), nullable=True, comment='部门名称'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('leader', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系方式'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态(1开启,0关闭)'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='详细地址'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_dept')
    # ### end Alembic commands ###
