"""empty message

Revision ID: b160d593d4a3
Revises: 934bd0330c8b
Create Date: 2021-02-20 00:33:04.980392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b160d593d4a3'
down_revision = '934bd0330c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('name', mysql.CHAR(collation='utf8mb4_bin', length=50), nullable=False))
    # ### end Alembic commands ###
