"""empty message

Revision ID: b5f015728218
Revises: 54d99d1873c3
Create Date: 2021-02-19 23:54:54.624749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f015728218'
down_revision = '54d99d1873c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('href', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'href')
    # ### end Alembic commands ###
