"""empty message

Revision ID: ce8825111f8f
Revises: 59add0790978
Create Date: 2021-03-11 22:41:25.156430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8825111f8f'
down_revision = '59add0790978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role_power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('power_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['power_id'], ['admin_power.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['admin_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_power')
    # ### end Alembic commands ###
