"""empty message

Revision ID: e79f59cc0e0d
Revises: b160d593d4a3
Create Date: 2021-02-20 00:33:17.165006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79f59cc0e0d'
down_revision = 'b160d593d4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'name')
    # ### end Alembic commands ###
