"""empty message

Revision ID: f1f04ea373ac
Revises: e79f59cc0e0d
Create Date: 2021-02-23 10:45:56.498316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1f04ea373ac'
down_revision = 'e79f59cc0e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ptype', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v0', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v1', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v2', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v3', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v4', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.Column('v5', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
