"""empty message

Revision ID: f662c7a20328
Revises: e7fec4ba5135
Create Date: 2021-03-04 22:15:43.471764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f662c7a20328'
down_revision = 'e7fec4ba5135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_admin_log', sa.Column('method', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_admin_log', 'method')
    # ### end Alembic commands ###
